baseURL = "https://demo.hugp/"
languageCode = "en-au"
title = "Welcome to the Demo"

# disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[taxonomies]
  category = "categories"

[params]
  localphone = "(03) 9191 1234"
  description = "A hugo site description"

[permalinks]
  posts = "/:section/:title/"
